---
title: "data_structure"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_structure}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(xxx)
library(tsibble)
library(sf)
library(ozmaps)
```

# Motivation for a new data structure:

```{r}
climate <- climate_monthly %>% head(100)

# build a tsibble
climate_tsibble <- climate %>% 
  mutate(date = yearmonth(date)) %>% 
  as_tsibble(key = c(station, param), index = date)

# build an sf from tsibble (can also build from tibble)
climate_sf <- climate_tsibble %>% filter(!is.na(lat)) %>% 
  st_as_sf(coords = c("long", "lat"), crs = st_crs(ozmap_country))

# spatial join returns an tibble/ sf
a <- climate_sf %>% 
  st_join(ozmap_states, join = st_within)
class(a) 

# turning it to tsibble again loses the sf structure
b <- a %>% as_tsibble(index = date, key = c(station, param))
class(b)

# hence would be nice to have a data structure that houses both tsibble and sf (with additional operations)
```
