---
title: "hierarchical"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cubble)
```

```{r}
set.seed(123)
climate <- climate_large %>% 
  ll_join(ozmaps::abs_ste %>% rename(state = NAME)) %>% 
  filter(!is.na(state)) %>% 
  slice_sample(n = 20) %>% 
  mutate(ts = list(as_tibble(ts)))

sample %>% group_by(NAME)

sample %>% 
  add_hier_idx(NAME) %>% 
  stretch() %>% 
  migrate(.within, .group, .id, NAME) %>% 
  ggplot(aes(x = date, y = tmax, color = .within)) + 
  geom_line() +
  facet_wrap(vars(NAME)) + 
  scale_x_date(date_labels = "%b") + 
  scale_color_brewer(palette = "Dark2") + 
  theme_bw()
```

```{r}
world <- weatherdata::world_sample %>% 
  filter(country %in% c("Australia", "Germany", "United States", "Spain", "France")) %>% 
  #add_hier_idx(country) %>% 
  stretch() %>% 
  filter(lubridate::year(date) == 2020) %>% 
  mutate(tmax = tmax / 10) %>% 
  migrate(country, continent) %>% 
  switch_key(country)

by_country <- world %>% 
  group_by(date) %>% 
  summarise(tmax = mean(tmax, na.rm = TRUE))


world %>% 
  ggplot(aes(x = date, y = tmax)) + 
  geom_line(aes(group = id), color = "grey70") +
  geom_line(data = by_country, color = "navyblue") + 
  facet_wrap(vars(country)) + 
  scale_x_date(date_labels = "%b") + 
  #scale_color_brewer(palette = "Dark2") + 
  #colorspace::scale_color_discrete_qualitative(palette = "Dark2", n = 10) + 
  theme_bw()
```

